// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as Nfa$ReasonReNfa from "./Nfa.bs.js";
import * as CharMap$ReasonReNfa from "./CharMap.bs.js";
import * as CharSet$ReasonReNfa from "./CharSet.bs.js";
import * as StateMap$ReasonReNfa from "./StateMap.bs.js";
import * as StateSet$ReasonReNfa from "./StateSet.bs.js";
import * as RabinScott$ReasonReNfa from "./RabinScott.bs.js";

function reverse(dfa) {
  return Nfa$ReasonReNfa.set_finals(Curry._1(StateSet$ReasonReNfa.singleton, dfa[/* start */3]), Curry._3(StateMap$ReasonReNfa.fold, (function (src, char_map, nfa) {
                    return Curry._3(CharMap$ReasonReNfa.fold, (function ($$char, dst, nfa) {
                                  return Nfa$ReasonReNfa.add_transition(/* tuple */[
                                              dst,
                                              Curry._1(CharSet$ReasonReNfa.singleton, $$char),
                                              src
                                            ], nfa);
                                }), char_map, nfa);
                  }), dfa[/* transitions */2], Nfa$ReasonReNfa.singleton(dfa[/* finals */4])));
}

function minimize(dfa) {
  return RabinScott$ReasonReNfa.determinize(reverse(RabinScott$ReasonReNfa.determinize(reverse(dfa))));
}

export {
  reverse ,
  minimize ,
  
}
/* Nfa-ReasonReNfa Not a pure module */
