// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE

import * as $$Map from "../node_modules/bs-platform/lib/es6/map.js";
import * as Char from "../node_modules/bs-platform/lib/es6/char.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as Caml_option from "../node_modules/bs-platform/lib/es6/caml_option.js";

var include = $$Map.Make([Char.compare]);

var merge = include[6];

function union(f) {
  return Curry._1(merge, (function (k, x, y) {
                if (x !== undefined) {
                  var v = Caml_option.valFromOption(x);
                  if (y !== undefined) {
                    return Curry._3(f, k, v, Caml_option.valFromOption(y));
                  } else {
                    return Caml_option.some(v);
                  }
                } else if (y !== undefined) {
                  return Caml_option.some(Caml_option.valFromOption(y));
                } else {
                  return undefined;
                }
              }));
}

var empty = include[0];

var is_empty = include[1];

var mem = include[2];

var add = include[3];

var singleton = include[4];

var remove = include[5];

var compare = include[7];

var equal = include[8];

var iter = include[9];

var fold = include[10];

var for_all = include[11];

var exists = include[12];

var filter = include[13];

var partition = include[14];

var cardinal = include[15];

var bindings = include[16];

var min_binding = include[17];

var max_binding = include[18];

var choose = include[19];

var split = include[20];

var find = include[21];

var map = include[22];

var mapi = include[23];

export {
  empty ,
  is_empty ,
  mem ,
  add ,
  singleton ,
  remove ,
  merge ,
  compare ,
  equal ,
  iter ,
  fold ,
  for_all ,
  exists ,
  filter ,
  partition ,
  cardinal ,
  bindings ,
  min_binding ,
  max_binding ,
  choose ,
  split ,
  find ,
  map ,
  mapi ,
  union ,
  
}
/* include Not a pure module */
