// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as Int32 from "../node_modules/bs-platform/lib/es6/int32.js";
import * as Caml_obj from "../node_modules/bs-platform/lib/es6/caml_obj.js";
import * as CharSet$ReasonReNfa from "./CharSet.bs.js";
import * as Caml_builtin_exceptions from "../node_modules/bs-platform/lib/es6/caml_builtin_exceptions.js";

function compare(param, param$1) {
  return Caml_obj.caml_compare(param[1], param$1[1]);
}

function example(char_list, state) {
  return /* tuple */[
          CharSet$ReasonReNfa.example(char_list),
          state
        ];
}

function to_string(param) {
  return CharSet$ReasonReNfa.to_string(param[0]) + ("<sub>" + (Int32.to_string(param[1]) + "</sub>"));
}

function test(param) {
  var a = example(/* :: */[
        /* "a" */97,
        /* [] */0
      ], 0);
  var b = example(/* :: */[
        /* "b" */98,
        /* [] */0
      ], 0);
  if (compare(a, b) !== 0) {
    throw [
          Caml_builtin_exceptions.assert_failure,
          /* tuple */[
            "Letter.re",
            17,
            2
          ]
        ];
  }
  if (to_string(a) === "a<sub>0</sub>") {
    return 0;
  } else {
    throw [
          Caml_builtin_exceptions.assert_failure,
          /* tuple */[
            "Letter.re",
            18,
            2
          ]
        ];
  }
}

export {
  compare ,
  example ,
  to_string ,
  test ,
  
}
/* CharSet-ReasonReNfa Not a pure module */
