// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as StateSet$ReasonReNfa from "./StateSet.bs.js";
import * as Caml_builtin_exceptions from "../node_modules/bs-platform/lib/es6/caml_builtin_exceptions.js";
import * as CharMapStateSet$ReasonReNfa from "./CharMapStateSet.bs.js";

function accept(nfa, inp) {
  var _cur_states = nfa[/* start */0];
  var _param = inp;
  while(true) {
    var param = _param;
    var cur_states = _cur_states;
    if (param) {
      var cur_char = param[0];
      _param = param[1];
      _cur_states = Curry._3(StateSet$ReasonReNfa.fold, (function(cur_char){
          return function (dst) {
            var tmp;
            try {
              tmp = Curry._2(CharMapStateSet$ReasonReNfa.find, cur_char, Curry._1(nfa[/* next */2], dst));
            }
            catch (exn){
              if (exn === Caml_builtin_exceptions.not_found) {
                tmp = StateSet$ReasonReNfa.empty;
              } else {
                throw exn;
              }
            }
            return Curry._1(StateSet$ReasonReNfa.union, tmp);
          }
          }(cur_char)), cur_states, StateSet$ReasonReNfa.empty);
      continue ;
    } else {
      return !Curry._1(StateSet$ReasonReNfa.is_empty, Curry._2(StateSet$ReasonReNfa.inter, cur_states, nfa[/* finals */1]));
    }
  };
}

export {
  accept ,
  
}
/* StateSet-ReasonReNfa Not a pure module */
