// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as Format from "../node_modules/bs-platform/lib/es6/format.js";
import * as Regex$ReasonReNfa from "./Regex.bs.js";
import * as Nfa_dot$ReasonReNfa from "./Nfa_dot.bs.js";

function regexp2dot(regexp) {
  var re = Regex$ReasonReNfa.parse(regexp);
  var nfa = Regex$ReasonReNfa.compile(re);
  var digraph = Nfa_dot$ReasonReNfa.digraph_of_nfa(nfa);
  return Curry._2(Format.asprintf(/* Format */[
                  /* Alpha */Block.__(15, [/* Formatting_lit */Block.__(17, [
                          /* Flush_newline */4,
                          /* End_of_format */0
                        ])]),
                  "%a@."
                ]), Nfa_dot$ReasonReNfa.format_digraph, digraph);
}

var regexp2parseTree = Regex$ReasonReNfa.regexp2parseTree;

function nullability(regexp) {
  return Regex$ReasonReNfa.l(Regex$ReasonReNfa.annotate(Regex$ReasonReNfa.parse(regexp)));
}

var firsts = Regex$ReasonReNfa.firsts;

var lasts = Regex$ReasonReNfa.lasts;

var letterpairs = Regex$ReasonReNfa.letterpairs;

export {
  regexp2dot ,
  regexp2parseTree ,
  nullability ,
  firsts ,
  lasts ,
  letterpairs ,
  
}
/* Format Not a pure module */
