// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as Format from "../node_modules/bs-platform/lib/es6/format.js";
import * as Regex$ReasonReNfa from "./Regex.bs.js";
import * as Nfa_dot$ReasonReNfa from "./Nfa_dot.bs.js";

function analyze(regexp) {
  Regex$ReasonReNfa.counter[0] = 1;
  var parsed_regex = Regex$ReasonReNfa.parse(regexp);
  var compiled_regex = Regex$ReasonReNfa.compile(parsed_regex);
  return /* tuple */[
          Curry._2(Format.asprintf(/* Format */[
                    /* Alpha */Block.__(15, [/* Formatting_lit */Block.__(17, [
                            /* Flush_newline */4,
                            /* End_of_format */0
                          ])]),
                    "%a@."
                  ]), Nfa_dot$ReasonReNfa.format_digraph, Nfa_dot$ReasonReNfa.digraph_of_nfa(compiled_regex)),
          Regex$ReasonReNfa.regexp2parseTree(parsed_regex),
          compiled_regex[/* nullable */4],
          compiled_regex[/* firsts */5],
          compiled_regex[/* lasts */6],
          compiled_regex[/* factors */7],
          compiled_regex[/* annotated */3]
        ];
}

export {
  analyze ,
  
}
/* Format Not a pure module */
