// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as Letter$ReasonReNfa from "./Letter.bs.js";
import * as CharSet$ReasonReNfa from "./CharSet.bs.js";
import * as Nfa_dot$ReasonReNfa from "./Nfa_dot.bs.js";
import * as Glushkov$ReasonReNfa from "./Glushkov.bs.js";
import * as StateSet$ReasonReNfa from "./StateSet.bs.js";
import * as LetterSet$ReasonReNfa from "./LetterSet.bs.js";
import * as Letter2Set$ReasonReNfa from "./Letter2Set.bs.js";
import * as CharMapStateSet$ReasonReNfa from "./CharMapStateSet.bs.js";
import * as CharSetMapStateSet$ReasonReNfa from "./CharSetMapStateSet.bs.js";
import * as StateMapCharSetMapStateSet$ReasonReNfa from "./StateMapCharSetMapStateSet.bs.js";

function test(param) {
  console.log("testing...");
  CharSet$ReasonReNfa.test(/* () */0);
  StateSet$ReasonReNfa.test(/* () */0);
  Letter$ReasonReNfa.test(/* () */0);
  LetterSet$ReasonReNfa.test(/* () */0);
  Letter2Set$ReasonReNfa.test(/* () */0);
  CharMapStateSet$ReasonReNfa.test(/* () */0);
  CharSetMapStateSet$ReasonReNfa.test(/* () */0);
  StateMapCharSetMapStateSet$ReasonReNfa.test(/* () */0);
  Glushkov$ReasonReNfa.test(/* () */0);
  Nfa_dot$ReasonReNfa.test(/* () */0);
  console.log("OK!");
  return /* () */0;
}

export {
  test ,
  
}
/* Letter-ReasonReNfa Not a pure module */
